"""update lesson models

Revision ID: d8b453d9c969
Revises: c836d7a9e51d
Create Date: 2026-08-07 18:20:13.999618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b453d9c969'
down_revision: Union[str, Sequence[str], None] = 'c836d7a9e51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_days', 'scripture_references')
    op.create_index(op.f('ix_scripture_references_id'), 'scripture_references', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scripture_references_id'), table_name='scripture_references')
    op.add_column('lesson_days', sa.Column('scripture_references', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
